import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Inter_Tight } from 'next/font/google'

const inter = Inter_Tight({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KJV Bible',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}><h1><Link href={'/'}>KJV Bible</Link></h1>{children}</body>
    </html>
  )
}
